#!/bin/sh 
echo name,star,element,job,comment,solo_dps,total_dps
python adv/berserker.py -2
python adv/euden.py -2
python adv/karl.py -2
python adv/naveed.py -2
python adv/raemond.py -2
python adv/rodrigo.py -2
python adv/xander.py -2
python adv/zardin.py -2
python adv/addis.py -2
python adv/aoi.py -2
python adv/celliera.py -2
python adv/h_edward.py -2
python adv/ieyasu.py -2
python adv/jurota.py -2
python adv/melody.py -2
python adv/mikoto.py -2
python adv/musashi.py -2
python adv/taro.py -2
python adv/althemia.py -2
python adv/amane.py -2
python adv/d_xander.py -2
python adv/kleimann.py -2
python adv/lily.py -2
python adv/lucretia.py -2
python adv/maribelle.py -2
python adv/nicolas.py -2
python adv/sinoa.py -2
python adv/xania.py -2
python adv/d_cleo.py -2
python adv/ezelith.py -2
python adv/francesca.py -2
python adv/irfan.py -2
python adv/luther.py -2
python adv/melsa.py -2
python adv/orion.py -2
python adv/orsem.py -2
python adv/renelle.py -2
python adv/vida.py -2
python adv/vice.py -2
python adv/erik.py -2
python adv/johanna.py -2
python adv/julietta.py -2
python adv/karina.py -2
python adv/linus.py -2
python adv/pietro.py -2
python adv/ranzal.py -2
python adv/rex.py -2
python adv/sazanka.py -2
python adv/vanessa.py -2
python adv/aeleen.py -2
python adv/alain.py -2
python adv/botan.py -2
python adv/cibella.py -2
python adv/elisanne.py -2
python adv/h_elisanne.py -2
python adv/malka.py -2
python adv/pia.py -2
python adv/ryozen.py -2
python adv/xainfried.py -2
python adv/zace.py -2
python adv/d_nefaria.py -2
python adv/eleonora.py -2
python adv/elias.py -2
python adv/hawk.py -2
python adv/joe.py -2
python adv/louise.py -2
python adv/luca.py -2
python adv/malora.py -2
python adv/nefaria.py -2
python adv/philia.py -2
python adv/rawn.py -2
python adv/waike.py -2
